const rootsVerified = 
[["אכל","pa'al"],
["סבר","hiph'il"],
["דבר","pi'el"],
["ראה","pa'al"],
["הלך","pa'al"],
["כתב","pa'al"],
["חכה","pi'el"],
["בוא","pa'al"],
["אהב","pa'al"],
["שתה","pa'al"],
["קרא","pa'al"],
["רצה","pa'al"],
["בשל","pi'el"],
["אפה","pa'al"],
["לבש","pa'al"],
["נעל","pa'al"],
["חבש","pa'al"],
["ענד","pa'al"],
["שים","pa'al"],
["רכב","hiph'il"],
["גרב","pa'al"],
["צבע","pa'al"],
["ספר","pa'al"],
["שאל","pa'al"],
["ענה","pa'al"],
["למד","pa'al"],
["למד","pi'el"],
["תרגל","pi'el"],
["טיל","pi'el"],
["רכב","pa'al"],
["נהג","pa'al"],
["שוט","pa'al"],
["טוס","pa'al"],
["נסע","pa'al"],
["פלג","hiph'il"],
["שחה","pa'al"],
["אמר","pa'al"],
["נגע","pa'al"],
["ישן","pa'al"],
["שמע","pa'al"],
["עבד","pa'al"],
["מצא","pa'al"],
["עשה","pa'al"],
["תמך","pa'al"],
["לקח","pa'al"],
["ידע","pa'al"],
["מכר","pa'al"],
["קנה","pa'al"],
["רשם","pa'al"],
["כאב","pa'al"],
["פתח","pa'al"],
["נתן","pa'al"],
["סגר","pa'al"],
["כעס","pa'al"],
["שמר","pa'al"],
["חשב","pa'al"],
["חזר","pa'al"],
["זכר","pa'al"],
["רוץ","pa'al"],
["כלל","pa'al"],
["נוח","pa'al"],
["שיר","pa'al"],
["רקד","pa'al"],
["עזר","pa'al"],
["שנא","pa'al"],
["עזב","pa'al"],
["שקל","pa'al"],
["חתם","pa'al"],
["עמד","pa'al"],
["ישב","pa'al"],
["שכח","pa'al"],
["חתך","pa'al"],
["יצר","pa'al"],
["גדל","pa'al"],
["בהה","pa'al"],
["בדק","pa'al"],
["שלח","pa'al"],
["שכר","pa'al"],
["יצא","pa'al"],
["צפה","pa'al"],
["נכר","hiph'il"],
["הפך","pa'al"],
["שבר","pa'al"],
["גנב","pa'al"],
["ברח","pa'al"],
["בקש","pi'el"],
["שלם","pi'el"],
["פספס","pi'el"],
["שחק","pi'el"],
["ספר","pi'el"],
["עצב","pi'el"],
["שנה","pi'el"],
["נסה","pi'el"],
["קוה","pi'el"],
["חפש","pi'el"],
["גדל","pi'el"],
["סמן","pi'el"],
["אחל","pi'el"],
["ערבב","pi'el"],
["כבד","pi'el"],
["סדר","pi'el"],
["יבש","pi'el"],
["יבא","pi'el"],
["חמם","pi'el"],
["מלא","pi'el"],
["בזבז","pi'el"],
["בקר","pi'el"],
["קבל","pi'el"],
["רחם","pi'el"],
["קנא","pi'el"],
["טפס","pi'el"],
["נצח","pi'el"],
["אמן","pi'el"],
["שקר","pi'el"],
["אחר","pi'el"],
["ספק","pi'el"],
["סים","pi'el"],
["שכנע","pi'el"],
["אבד","pi'el"],
["צלם","pi'el"],
["אמץ","pi'el"],
["פחד","pi'el"],
["אשר","pi'el"],
["גלה","pi'el"],
["גלח","pi'el"],
["חדש","pi'el"],
["ברך","pi'el"],
["תאר","pi'el"],
["תקן","pi'el"],
["היה","pa'al"],
["קשב","hiph'il"],
["ראה","hiph'il"],
["אזן","hiph'il"],
["יצע","hiph'il"],
["רגש","hiph'il"],
["כון","hiph'il"],
["אמן","hiph'il"],
["סכם","hiph'il"],
["תחל","hiph'il"],
["נגע","hiph'il"],
["ידה","hiph'il"],
["עבר","hiph'il"],
["צלח","hiph'il"],
["חזר","hiph'il"],
["נשג","hiph'il"],
["שכר","hiph'il"],
["מלץ","hiph'il"],
["חזק","hiph'il"],
["נפק","hiph'il"],
["נוח","hiph'il"],
["יפע","hiph'il"],
["יסף","hiph'il"],
["נגש","hiph'il"],
["משך","hiph'il"],
["יצג","hiph'il"],
["כרז","hiph'il"],
["זמן","hiph'il"],
["רשה","hiph'il"],
["זכר","hiph'il"],
["עדף","hiph'il"],
["תאם","hiph'il"],
["חלט","hiph'il"],
["בין","hiph'il"],
["כול","hiph'il"],
["חלף","hiph'il"],
["ערך","hiph'il"],
["בוא","hiph'il"],
["נגד","hiph'il"],
["גור","pa'al"],
["סבל","pa'al"],
["מנע","pa'al"],
["ציר","pi'el"],
["שפע","hiph'il"],
["גדל","hiph'il"],
["שפר","pi'el"],
["גדר","hiph'il"],
["כסה","pi'el"],
["אפשר","pi'el"],
["פתח","pi'el"],
["מות","pa'al"],
["גוב","hiph'il"],
["פסד","hiph'il"],
["שמש","hitpa'el"],
["אשש","hitpa'el"],
["פגש","pa'al"],
["עצר","pa'al"],
["שאר","nif'al"],
["בנה","pa'al"],
["גרם","nif'al"],
["חמץ","hiph'il"],
["נפל","pa'al"],
["קפץ","pa'al"],
["קלח","hitpa'el"],
["גלח","hitpa'el"],
["ספר","hitpa'el"],
["סכל","hitpa'el"],
["קשר","hitpa'el"],
["חזק","hitpa'el"],
["אמן","hitpa'el"],
["קרב","hitpa'el"],
["חנך","hitpa'el"],
["חנן","hitpa'el"],
["גבר","hitpa'el"],
["סים","hitpa'el"],
["געגע","hitpa'el"],
["סבב","hitpa'el"],
["קרר","hitpa'el"],
["חמם","hitpa'el"],
["זקן","hitpa'el"],
["חבא","hitpa'el"],
["שכר","hitpa'el"],
["שנה","hitpa'el"],
["אחד","hitpa'el"],
["חבר","hitpa'el"],
["נתק","hitpa'el"],
["יעצ","hitpa'el"],
["כון","hitpa'el"],
["צרף","hitpa'el"],
["מדד","hitpa'el"],
["עלם","hitpa'el"],
["פלל","hitpa'el"],
["נצל","hitpa'el"],
["בלבל","hitpa'el"],
["עמל","hitpa'el"],
["בחר","pa'al"],
["ראה","nif'al"],
["כשל","nif'al"],
["גמר","nif'al"],
["כנס","nif'al"],
["שמע","nif'al"],
["סגר","nif'al"],
["פתח","nif'al"],
["אכל","nif'al"],
["כתב","nif'al"],
["קרא","nif'al"],
["פגש","nif'al"],
["שאל","nif'al"],
["עשה","nif'al"],
["נתן","nif'al"],
["עלם","nif'al"],
["פרד","nif'al"],
["שרף","nif'al"],
["שלח","nif'al"],
["פגע","nif'al"],
["אמר","nif'al"],
["הנה","nif'al"],
["פצץ","hitpa'el"],
["חתן","hitpa'el"],
["לון","hitpa'el"],
["פשט","hitpa'el"],
["רחץ","hitpa'el"],
["פסק","hiph'il"],
["נדב","hitpa'el"],
["עלל","hitpa'el"],
["ירד","pa'al"],
["צער","hitpa'el"],
["עלב","nif'al"],
["נשק","pi'el"],
["חבק","pi'el"],
["נחם","pi'el"],
["בכה","pa'al"],
["להב","hitpa'el"],
["ערץ","hiph'il"],
["בשל","pu'al"],
["קבל","hiph'il"],
["נסה","pu'al"],
["ערבב","pu'al"],
["בזבז","pu'al"],
["שנה","pu'al"],
["דבר","pu'al"],
["סים","pu'al"],
["שכנע","pu'al"],
["שתף","pu'al"],
["קבל","pu'al"],
["סדר","pu'al"],
["מלא","pu'al"],
["בין","huf'al"],
["חלף","huf'al"],
["רכב","huf'al"],
["זמן","huf'al"],
["פרע","hiph'il"],
["פרע","huf'al"],
["צלח","huf'al"],
["גבל","hiph'il"],
["גבל","huf'al"],
["חלט","huf'al"],
["שפע","huf'al"],
["דאג","hiph'il"],
["דאג","huf'al"],
["תאם","huf'al"],
["סבר","huf'al"],
["דכא","pi'el"],
["דכא","pu'al"],
["אשר","pu'al"],
["נשק","pu'al"],
["נחם","pu'al"],
["חבק","pu'al"],
["שעמם","pi'el"],
["שעמם","pu'al"],
["דחה","pa'al"],
["נשק","hitpa'el"],
["חבק","hitpa'el"],
["פתע","hiph'il"],
["פתע","huf'al"],
["צפה","pi'el"],
["צפה","pu'al"],
["בוך","hiph'il"],
["זכר","nif'al"],
["גמר","pa'al"],
["כשל","pa'al"],
["יכל","pa'al"],
["תהה","pa'al"],
["נבע","hiph'il"],
["טעה","pa'al"],
["חיה","pa'al"],
["חלץ","pi'el"],
["לכד","pa'al"],
["בצע","pi'el"],
["עלף","hitpa'el"],
["חשמל","hitpa'el"],
["טבע","pa'al"],
["אבד","nif'al"],
["אבד","pa'al"],
["יצב","hiph'il"],
["תקף","pa'al"],
["רשם","nif'al"],
["נגש","huf'al"],
["נוף","hiph'il"],
["חתם","nif'al"],
["מחק","nif'al"],
["זהה","pi'el"],
["עלה","pa'al"],
["פקר","huf'al"],
["חסן","hitpa'el"]]


const rulesDefault = 
[[1,"","","tav@suffix","yod+finalMem@suffix","vav+tav@suffix","tav+yod@suffix","nun+vav@suffix","tav@suffix","tav@suffix","tav+finalMem@suffix","tav+finalNun@suffix","","he@suffix","vav@suffix","alef@prefix","nun@prefix","tav@prefix","tav@prefix, yod@suffix","tav@prefix, vav@suffix","tav@prefix, nun+he@suffix","yod@prefix","tav@prefix","yod@prefix, vav@suffix","tav@prefix, nun+he@suffix","","yod@suffix","vav@suffix","nun+he@suffix","lamed@prefix"],
[2,"pa'al","vav@2","vav@2","vav@2","vav@2","","","","","","","","","","","","","","","","","","","","","","","","vav@3"],
[3,"pi'el","mem@prefix","mem@prefix","mem@prefix","mem@prefix","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","","","","","","","","","","","","","","",""],
[4,"hiph'il","mem@prefix, yod@3","mem@prefix, yod@3, he@suffix","mem@prefix, yod@3","mem@prefix, yod@3","he@prefix","he@prefix","he@prefix","he@prefix","he@prefix","he@prefix","he@prefix, yod@3","he@prefix, yod@3","he@prefix, yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","","yod@3","yod@3","yod@3","","he@start","he@start, yod@3","he@start, yod@3","he@start","he@start, yod@3"],
[5,"hitpa'el","mem+tav@prefix","mem+tav@prefix","mem+tav@prefix","mem+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","he+tav@prefix","tav@start","tav@start","tav@start","tav@start","tav@start","tav@start","tav@start","tav@start","tav@start","tav@start","he+tav@start","he+tav@start","he+tav@start","he+tav@start","he+tav@start"],
[6,"huf'al","mem+vav@prefix","mem+vav@prefix","mem+vav@prefix","mem+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","he+vav@prefix","vav@start","vav@start","vav@start","vav@start","vav@start","vav@start","vav@start","vav@start","vav@start","vav@start","-","-","-","-","-"],
[7,"pu'al","mem@prefix, vav@2","mem@prefix, vav@2","mem@prefix, vav@2","mem@prefix, vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","-","-","-","-","-"],
[8,"nif'al","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","nun@prefix","","yod@start","yod@start","yod@start","yod@start","yod@start","yod@start","yod@start","yod@start","yod@start","he+yod@start","he+yod@start","he+yod@start","he+yod@start","he+yod@start"],
[100,"not nif'al, end=he","","@suffix","~end","~end","yod~end","yod~end","yod~end","yod~end","yod~end","yod~end","","tav~end","~end","","","","~end","~end","yod~end","","","~3","yod~end","","~end","~end","yod~end","tav~end"],
[101,"pa'al, 2=vav","~2","~2, he@suffix","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","","","","","","","","","","","","","","","@3"],
[102,"pa'al, end=tav","","","","","~end","","~end","~end","~end","~end","","","","","","","","","","","","","","","","","",""],
[103,"pa'al, 2=yod, not end=he","~2","~2, he@suffix","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","","","","","","~2","","","","~2","","","","~2","@3"],
[104,"pa'al, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","","","","~end",""],
[105,"pi'el, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","","","","~end",""],
[106,"pi'el, 2=yod","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2"],
[107,"pi'el, 1=yod","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","","yod@2","","yod@2","","","","","yod@2"],
[108,"pi'el, end=he","","","","","","","","","","","","","","","","","","","","","","","","","","","","vav@3"],
[109,"pi'el, 2=vav, end=he","vav@3","vav@3","vav@3","","vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","","vav@3","vav@3","vav@3","vav@3","","vav@3","vav@3","vav@3","","vav@3","vav@2","vav@2","","vav@3",""],
[110,"hiph'il, end=he","@3","@3","@3","@3","","","","","","","@3","@3","@3","@3","@3","@3","@3, ~end","@3, ~end","@3","@3","@3","@3, ~end","@3","","@3","@3","@3","vav@3"],
[111,"hiph'il, 2=vav","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2"],
[112,"hiph'il, 2=yod","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2"],
[113,"huf'al, 2=yod","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","~2","-","-","-","-","-"],
[114,"hiph'il, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","","","","~end",""],
[115,"huf'al, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","-","-","-","-","-"],
[116,"nif'al, end=he","","yod~end","~end","~end","yod~end","yod~end","yod~end","yod~end","yod~end","yod~end","","tav~end","~end","","","","~end","~end","yod~end","","","~end","yod~end","","~end","~end","yod~end","vav+tav~end"],
[117,"nif'al, 1=alef","","","","","","","","","","","","","","yod@start","","","","","","","","","","","","","",""],
[118,"nif'al, 1=ayin","","","","","","","","","","","","","","yod@start","","","","","","","","","","","","","",""],
[119,"nif'al, 1=resh","","","","","","","","","","","","","","yod@start","","","","","","","","","","","","","",""],
[120,"nif'al, 1=he","","","","","","","","","","","","","","yod@start","","","","","","","","","","","","","",""],
[121,"nif'al, 1=het","","","","","","","","","","","","","","yod@start","","","","","","","","","","","","","",""],
[122,"nif'al, 1=nun","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","","","","","","","","","","","","","","",""],
[123,"nif'al, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","","","","~end",""],
[124,"hitpa'el, 2=3","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2","vav@2"],
[125,"hitpa'el, 1=shin","mem@prefix, tav@2","mem@prefix, tav@2","mem@prefix, tav@2","mem@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2"],
[126,"hitpa'el, 1=samekh","mem@prefix, tav@2","mem@prefix, tav@2","mem@prefix, tav@2","mem@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","he@prefix, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2","he@start, tav@2"],
[127,"hitpa'el, 1=zayin","mem@prefix, dalet@2","mem@prefix, dalet@2","mem@prefix, dalet@2","mem@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","he@prefix, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","@start, dalet@2","he@start, dalet@2","he@start, dalet@2","he@start, dalet@2","he@start, dalet@2","he@start, dalet@2"],
[128,"hitpa'el, 1=tsadi","mem@prefix, tet@2","mem@prefix, tet@2","mem@prefix, tet@2","mem@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","he@prefix, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","@start, tet@2","he@start, tet@2","he@start, tet@2","he@start, tet@2","he@start, tet@2","he@start, tet@2"],
[129,"hitpa'el, end=finalNun","","","","","","~end","","","","","","","","","","","","","~end","","","","~end","","","","~end",""],
[130,"hitpa'el, 2=yod","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3","yod@3"],
[131,"hitpa'el, 1=yod","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2","yod@2"],
[132,"hitpa'el, end=he","","","","","","","","","","","","","","","","","","","","","","","","","","","","vav@3"],
[133,"pa'al, 1=alef","","","","","","","","","","","","","","@prefix, vav@2","","","","","","","","","","","","","",""],
[1000,"הלך/pa'al, ישב/pa'al, יצא/pa'al, ידע/pa'al, ירד/pa'al","","","","","","","","","","","","","","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1, @3, tav@end"],
[1001,"נסע/pa'al, נגע/pa'al, לקח/pa'al, נתן/pa'al, יצר/pa'al, נפל/pa'al","","","","","","","","","","","","","","~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","yod~1","~1","~1","~1","~1",""],
[1002,"נפל/pa'al","","","","","","","","","","","","","","","","","","","","","","","","","","","","yod~1"],
[1003,"לקח/pa'al, נגע/pa'al","","","","","","","","","","","","","","","","","","","","","","","","","","","","~1, @3, tav@end"],
[1004,"נתן/pa'al","","","","","~end","","~end","~end","~end","~end","","","","","","","","","","","","","","","","","","~1, ~3, tav@end"],
[1005,"חיה/pa'al","@2, ~end","@2","@2","@2","","","","","","","~end","yod+tav~end","","","","","","","","","","","","","","","",""],
[1006,"אכל/pa'al, אמר/pa'al, אבד/pa'al","","","","","","","","","","","","","","","","","","","","","","","","vav@3","","","vav@3",""],
[1007,"אמר/pa'al","","","","","","","","","","","","","","","","","","","","","","","","","","","","vav~1, @3"],
[1008,"נעל/pa'al, כתב/pa'al, חבש/pa'al, ענד/pa'al, גרב/pa'al, ספר/pa'al, עבד/pa'al, תמך/pa'al, מכר/pa'al, רשם/pa'al, סגר/pa'al, שמר/pa'al, חשב/pa'al, חזר/pa'al, זכר/pa'al, כלל/pa'al, רקד/pa'al, עזר/pa'al, עזב/pa'al, שקל/pa'al, חתם/pa'al, עמד/pa'al, חתך/pa'al, יצר/pa'al, נפל/pa'al , בדק/pa'al, שכר/pa'al, הפך/pa'al, שבר/pa'al, גנב/pa'al, סבל/pa'al, פגש/pa'al, עצר/pa'al, קפץ/pa'al, גמר/pa'al, כשל/pa'al, לכד/pa'al, תקף/pa'al","","","","","","","","","","","","","","vav@3","vav@3","vav@3","","","vav@3","vav@3","vav@3","","vav@3","vav@3","","","vav@3",""],
[1009,"ישן/pa'al, גדל/pa'al","@2","@2, he@suffix","@2","@2","","","","","","","","","","","","","","","","","","","","","","","",""],
[1010,"יכל/pa'al","@2, vav@3","@2, vav@3, he@suffix","@2, vav@3","@2, vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","vav@3","","","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","~1, vav@2","-","-","-","-","he+yod+vav+tav+space@start"],
[1011,"נכר/hiph'il, נגע/hiph'il, יצע/hiph'il, נשג/hiph'il, נפק/hiph'il, נגש/hiph'il, יצג/hiph'il, נגד/hiph'il, נבע/hiph'il, יצב/hiph'il, נגש/huf'al","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1","~1"],
[1012,"היה/pa'al","vav+vav~2","vav+vav~2","vav+vav~2","vav~2","","","","","","","","yod@2","","","","","","","","","","","","","","","",""],
[1013,"ידה/hiph'il, יפע/hiph'il, יסף/hiph'il","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1","vav~1"],
[1014,"נוח/pa'al","","","","","","","","","","","","","","","","","","","~2","","","","~2","","","","~2",""],
[1015,"סבב/hitpa'el","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2","tav+vav@2"],
[1016,"קרר/hitpa'el, פלל/hitpa'el, חנן/hitpa'el, חמם/hitpa'el, עלל/hitpa'el","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2","@2"],
[1017,"כון/hitpa'el, לון/hitpa'el","nun@3","nun@3","nun@3","nun@3","nun@3","@end","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","nun@3","@end","nun@3","nun@3","nun@3","@end","nun@3","nun@3","nun@3","@end","nun@3"],
[1018,"הנה/nif'al","","","","","","","","","","","","","","","","","","","","","","","","","","","","yod@start"]]


module.exports = {rootsVerified, rulesDefault};
